# Generated by Django 4.2.6 on 2024-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('ten_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelve_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yoe', models.IntegerField()),
            ],
            options={
                'db_table': 'Apply',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('requirements', models.TextField()),
                ('app_deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'Job',
            },
        ),
    ]
